package constants

// AlgDSA and related constants specify the standardized cryptographic algorithm identifiers to prevent hardcoded strings and ensure consistent reporting.
const (
	AlgDSA              = "DSA"
	AlgRSA              = "RSA"
	AlgECDSA            = "ECDSA"
	AlgDH               = "DH"
	AlgRSAMD5           = "RSAMD5"
	AlgRSASHA1          = "RSASHA1"
	AlgDSANSEC3SHA1     = "DSA-NSEC3-SHA1"
	AlgRSASHA1NSEC3SHA1 = "RSASHA1-NSEC3-SHA1"
	AlgRSASHA256        = "RSASHA256"
	AlgRSASHA512        = "RSASHA512"
	AlgECCGOST          = "ECC-GOST"
	AlgECDSAP256SHA256  = "ECDSAP256SHA256"
	AlgECDSAP384SHA384  = "ECDSAP384SHA384"
	AlgED25519          = "ED25519"
	AlgED448            = "ED448"
	AlgIndirect         = "INDIRECT"
	AlgPrivateDNS       = "PRIVATEDNS"
	AlgPrivateOID       = "PRIVATEOID"
	AlgECDSALow         = "ECDSA_LOW"
	AlgDSALow           = "DSA_LOW"
	AlgRSALow           = "RSA_LOW"
	AlgEdDSA            = "EDDSA"
	AlgEdDSALow         = "EDDSA_LOW"
	AlgPQC              = "PQC"
	AlgEd25519SSH       = "Ed25519"
	AlgEd448SSH         = "Ed448"
	DigestSHA1          = "SHA-1"
	DigestSHA256        = "SHA-256"
	DigestSHA384        = "SHA-384"
	DigestGOSTR341194   = "GOST R 34.11-94"
)
