package constants

// FuncGetDomains and related constants define the available module function names, ensuring consistent routing and execution capabilities definitions.
const (
	FuncGetDomains          = "get_domains"
	FuncGetEmails           = "get_emails"
	FuncGetHosts            = "get_hosts"
	FuncGetASN              = "get_asn"
	FuncGetPTR              = "get_ptr"
	FuncGetTOR              = "get_tor"
	FuncGetRBL              = "get_rbl"
	FuncGetIP               = "get_ip"
	FuncGetCAA              = "get_caa"
	FuncGetNS               = "get_ns"
	FuncGetSOA              = "get_soa"
	FuncGetCNAME            = "get_cname"
	FuncCheckWildcard       = "check_wildcard"
	FuncGetDomainKey        = "get_domainkey"
	FuncGetDMARC            = "get_dmarc"
	FuncGetDKIM             = "get_dkim"
	FuncGetMX               = "get_mx"
	FuncGetTXT              = "get_txt"
	FuncGetSRV              = "get_srv"
	FuncGetNSEC             = "get_nsec"
	FuncGetLOC              = "get_loc"
	FuncGetHINFO            = "get_hinfo"
	FuncGetRP               = "get_rp"
	FuncGetURI              = "get_uri"
	FuncGetSVCB             = "get_svcb"
	FuncGetSSHFP            = "get_sshfp"
	FuncGetNAPTR            = "get_naptr"
	FuncGetTLSA             = "get_tlsa"
	FuncGetDNSKEY           = "get_dnskey"
	FuncGetDS               = "get_ds"
	FuncGetCERT             = "get_cert"
	FuncGetHIP              = "get_hip"
	FuncGetIPSECKEY         = "get_ipseckey"
	FuncGetIPInfo           = "get_ip_info"
	FuncGetIPAbuseContacts  = "get_ip_abuse_contacts"
	FuncGetASNPeers         = "get_asn_peers"
	FuncGetASNPrefixes      = "get_asn_prefixes"
	FuncGetASNInfo          = "get_asn_info"
	FuncGetASNAbuseContacts = "get_asn_abuse_contacts"
	FuncGetWhois            = "get_whois"
	FuncGetOpenpgpkey       = "get_openpgpkey"
	FuncGetSmimea           = "get_smimea"
	FuncPreflightDNS        = "preflight_dns"
	FuncGetIDBShodan        = "get_idb_shodan"
	FuncGetShodanAPIIP      = "get_shodan_api_ip"
	FuncGetShodanAPIDomain  = "get_shodan_api_domain"
	FuncGetVTApiData        = "get_vt_api_data"
	FuncGetCirclVuln        = "get_circl_vuln"
)
