package constants

// TagDNSOK and related constants define standardized tag values used by modules to report findings and routing prerequisites consistently.
const (
	TagDNSOK       = ".dns_ok"
	TagDNSBad      = ".dns_bad"
	TagMX          = "mx"
	TagNS          = "ns"
	TagSRV         = "srv"
	TagNAPTR       = "naptr"
	TagRP          = "rp"
	TagCNAME       = "cname"
	TagCAA         = "caa"
	TagHIP         = "hip"
	TagIPSECKEY    = "ipseckey"
	TagSan         = "san"
	TagWildcard    = "wildcard"
	TagPDNS        = "passive_dns"
	TagNSEC        = "nsec"
	TagReverseIP   = "reverse_ip"
	TagWhoisServer = "whois_server"
	TagSPF         = "spf"
	TagCTLog       = "ct_log"
	TagHistorical  = "historical"
	TagLinked      = "linked"
	TagSocial      = "social"
	TagScrape      = "scrape"
	TagCVE         = "cve"
	TagMalicious   = "malicious"
	TagSuspicious  = "suspicious"
	TagCompromised = "compromised"
	TagExploit     = "exploit"
	TagMalware     = "malware"
	TagPhishing    = "phishing"
)
